#!/bin/bash

# ============================================================================
# Hydrate Personal Data into Working Tree (Maintainer Tool)
# ============================================================================
# After `git checkout main` (or any non-personal branch), this pulls your
# personal-side data files into the working tree so `npm run dev` and
# `npm run build` produce a site populated with YOUR data — not the
# .example placeholders.
#
# Files are gitignored on `main`, so they cannot accidentally be committed.
#
# USAGE:
#   ./scripts/hydrate-personal-data.sh
#   # or
#   npm run hydrate
#
# WHAT IT COPIES (only files that exist on `personal`):
#   - resume.yaml
#   - client/public/manifest.json
#   - client/public/data/styled_name.txt
#   - client/public/data/neofetch.txt
#   - client/public/data/neofetch-small.txt
#   - client/public/data/skill-graph.json
#   - client/public/logo.png
#
# Generated artifacts (resume.json, resume.pdf, etc.) are NOT copied —
# they're regenerated by `npm run build` from resume.yaml.
# ============================================================================

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo -e "${RED}\xe2\x9c\x97${NC} Not in a git repository."
  exit 1
fi

# Verify `personal` ref exists locally; fall back to origin/personal.
if ! git rev-parse --verify --quiet refs/heads/personal > /dev/null 2>&1; then
  if git rev-parse --verify --quiet refs/remotes/origin/personal > /dev/null 2>&1; then
    echo -e "${CYAN}ℹ${NC} Local 'personal' ref missing — using origin/personal."
    PERSONAL_REF="origin/personal"
  else
    echo -e "${RED}✗${NC} No 'personal' branch found locally or on origin."
    echo -e "  Run: ${CYAN}git fetch origin personal${NC}"
    exit 1
  fi
else
  PERSONAL_REF="personal"
fi

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$CURRENT_BRANCH" == "personal" ]]; then
  echo -e "${YELLOW}⚠${NC}  You're already on 'personal' — nothing to hydrate."
  exit 0
fi

# Files to hydrate from personal. Generated artifacts excluded — they'll be
# regenerated by npm run build from resume.yaml.
PERSONAL_FILES=(
  "resume.yaml"
  "client/public/manifest.json"
  "client/public/data/styled_name.txt"
  "client/public/data/neofetch.txt"
  "client/public/data/neofetch-small.txt"
  "client/public/data/skill-graph.json"
  "client/public/logo.png"
)

echo -e "${CYAN}🪣  Hydrating personal data from '$PERSONAL_REF' into working tree...${NC}"
echo ""

PULLED=0
SKIPPED=0
for f in "${PERSONAL_FILES[@]}"; do
  if git show "$PERSONAL_REF:$f" > /dev/null 2>&1; then
    mkdir -p "$(dirname "$f")"
    git show "$PERSONAL_REF:$f" > "$f"
    echo -e "  ${GREEN}✓${NC} $f"
    PULLED=$((PULLED+1))
  else
    echo -e "  ${YELLOW}·${NC} $f  ${YELLOW}(not on personal — skipped)${NC}"
    SKIPPED=$((SKIPPED+1))
  fi
done

echo ""
echo -e "${GREEN}✓${NC} Hydrated $PULLED file(s) ($SKIPPED skipped) from $PERSONAL_REF"
echo ""
echo -e "${CYAN}ℹ${NC} These files are gitignored on '$CURRENT_BRANCH' — safe to leave"
echo -e "  in the working tree. Run ${CYAN}npm run dev${NC} or ${CYAN}npm run build${NC}"
echo -e "  with your real data."
